title: StickyIT
url: https://iamafram.github.io
author: Afram

remote_theme: mmistakes/minimal-mistakes@4.26.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

paginate: 5
paginate_path: "/page:num/"

collections:
  posts:
    output: true

defaults:
  - scope: {path: "" , type: "posts"}
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false